// This file is generated by Tools/cases_generator/partial_evaluator_generator.py
// from:
//   Python/optimizer_partial_evaluator_bytecodes.c
// Do not edit!

        case _NOP: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_PERIODIC: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _CHECK_PERIODIC_AT_END is not a viable micro-op for tier 2 */

        case _CHECK_PERIODIC_IF_NOT_YIELD_FROM: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _QUICKEN_RESUME is not a viable micro-op for tier 2 */

        /* _LOAD_BYTECODE is not a viable micro-op for tier 2 */

        case _RESUME_CHECK: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _MONITOR_RESUME is not a viable micro-op for tier 2 */

        case _LOAD_FAST_CHECK: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            if (sym_is_null(value)) {
                ctx->done = true;
            }
            value = GETLOCAL(oparg);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_FAST: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = GETLOCAL(oparg);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_FAST_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = GETLOCAL(oparg);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_FAST_AND_CLEAR: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = GETLOCAL(oparg);
            JitOptRef temp = sym_new_null(ctx);
            GETLOCAL(oparg) = temp;
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_CONST: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_SMALL_INT: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_FAST: {
            JitOptRef value;
            value = stack_pointer[-1];
            EMIT_OP_FROM_INST(this_instr);
            GETLOCAL(oparg) = value;
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP_NOP: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP_INT: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP_FLOAT: {
            JitOptRef value;
            value = stack_pointer[-1];
            if (PyJitRef_IsUnboxed(value)) {
                EMIT_OP(_POP_TOP_NOP, 0, 0, 0, 0);
            }
            else {
                EMIT_OP_FROM_INST(this_instr);
            }
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP_UNICODE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TWO: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _PUSH_NULL: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _END_FOR: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_ITER: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _END_SEND: {
            JitOptRef val;
            EMIT_OP_FROM_INST(this_instr);
            val = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = val;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _UNARY_NEGATIVE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _UNARY_NOT: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_BOOL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _TO_BOOL_INT: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _GUARD_NOS_LIST: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_LIST: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_SLICE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _TO_BOOL_LIST: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _TO_BOOL_NONE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _GUARD_NOS_UNICODE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_UNICODE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _TO_BOOL_STR: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _REPLACE_WITH_TRUE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _UNARY_INVERT: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _GUARD_NOS_INT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_INT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_NOS_OVERFLOWED: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_OVERFLOWED: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _BINARY_OP_MULTIPLY_INT: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_ADD_INT: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBTRACT_INT: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_NOS_FLOAT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_FLOAT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _BINARY_OP_MULTIPLY_FLOAT: {
            JitOptRef right;
            JitOptRef left;
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            if (PyJitRef_IsUnboxed(left) || PyJitRef_IsUnboxed(right)) {
                if (!PyJitRef_IsUnboxed(left)) {
                    EMIT_OP(_NOS_TO_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
                }
                if (!PyJitRef_IsUnboxed(right)) {
                    EMIT_OP(_TOS_TO_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
                }
                EMIT_OP(_BINARY_OP_MULTIPLY_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
            }
            else {
                EMIT_OP(_BINARY_OP_MULTIPLY_FLOAT_OUT_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
            }
            res = PyJitRef_SetUnbox(sym_new_type(ctx, &PyFloat_Type));
            l = left;
            r = right;
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_ADD_FLOAT: {
            JitOptRef right;
            JitOptRef left;
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            if (PyJitRef_IsUnboxed(left) || PyJitRef_IsUnboxed(right)) {
                if (!PyJitRef_IsUnboxed(left)) {
                    EMIT_OP(_NOS_TO_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
                }
                if (!PyJitRef_IsUnboxed(right)) {
                    EMIT_OP(_TOS_TO_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
                }
                EMIT_OP(_BINARY_OP_ADD_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
            }
            else {
                EMIT_OP(_BINARY_OP_ADD_FLOAT_OUT_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
            }
            res = PyJitRef_SetUnbox(sym_new_type(ctx, &PyFloat_Type));
            l = left;
            r = right;
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBTRACT_FLOAT: {
            JitOptRef right;
            JitOptRef left;
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            right = stack_pointer[-1];
            left = stack_pointer[-2];
            if (PyJitRef_IsUnboxed(left) || PyJitRef_IsUnboxed(right)) {
                if (!PyJitRef_IsUnboxed(left)) {
                    EMIT_OP(_NOS_TO_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
                }
                if (!PyJitRef_IsUnboxed(right)) {
                    EMIT_OP(_TOS_TO_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
                }
                EMIT_OP(_BINARY_OP_SUBTRACT_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
            }
            else {
                EMIT_OP(_BINARY_OP_SUBTRACT_FLOAT_OUT_TAGGED_DOUBLE, 0, 0, 0, this_instr->target);
            }
            res = PyJitRef_SetUnbox(sym_new_type(ctx, &PyFloat_Type));
            l = left;
            r = right;
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_ADD_UNICODE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_INPLACE_ADD_UNICODE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_BINARY_OP_EXTEND: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _BINARY_OP_EXTEND: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_SLICE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_SLICE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-4);
            stack_pointer += -4;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBSCR_LIST_INT: {
            JitOptRef res;
            JitOptRef ls;
            JitOptRef ss;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            ls = sym_new_not_null(ctx);
            ss = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = ls;
            stack_pointer[0] = ss;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBSCR_LIST_SLICE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBSCR_STR_INT: {
            JitOptRef res;
            JitOptRef s;
            JitOptRef i;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            s = sym_new_not_null(ctx);
            i = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = s;
            stack_pointer[0] = i;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_NOS_TUPLE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_TUPLE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_TUPLE_INT: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_NOS_DICT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TOS_DICT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_DICT: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBSCR_CHECK_FUNC: {
            JitOptRef getitem;
            EMIT_OP_FROM_INST(this_instr);
            getitem = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = getitem;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBSCR_INIT_CALL: {
            JitOptRef new_frame;
            EMIT_OP_FROM_INST(this_instr);
            new_frame = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = new_frame;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LIST_APPEND: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _SET_ADD: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_SUBSCR: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-3);
            stack_pointer += -3;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_SUBSCR_LIST_INT: {
            JitOptRef ls;
            JitOptRef ss;
            EMIT_OP_FROM_INST(this_instr);
            ls = sym_new_not_null(ctx);
            ss = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-3] = ls;
            stack_pointer[-2] = ss;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_SUBSCR_DICT: {
            JitOptRef st;
            EMIT_OP_FROM_INST(this_instr);
            st = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = st;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _DELETE_SUBSCR: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_INTRINSIC_1: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _CALL_INTRINSIC_2: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _RETURN_VALUE: {
            JitOptRef retval;
            JitOptRef res;
            retval = stack_pointer[-1];
            EMIT_OP_FROM_INST(this_instr);
            res = PyJitRef_StripReferenceInfo(retval);
            ctx->done = true;
            stack_pointer[-1] = res;
            break;
        }

        case _GET_AITER: {
            JitOptRef iter;
            EMIT_OP_FROM_INST(this_instr);
            iter = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            break;
        }

        case _GET_ANEXT: {
            JitOptRef awaitable;
            EMIT_OP_FROM_INST(this_instr);
            awaitable = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = awaitable;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GET_AWAITABLE: {
            JitOptRef iter;
            EMIT_OP_FROM_INST(this_instr);
            iter = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            break;
        }

        /* _SEND is not a viable micro-op for tier 2 */

        case _SEND_GEN_FRAME: {
            JitOptRef v;
            JitOptRef receiver;
            JitOptRef gen_frame;
            EMIT_OP_FROM_INST(this_instr);
            gen_frame = PyJitRef_NULL;
            ctx->done = true;
            stack_pointer[-1] = gen_frame;
            break;
        }

        case _YIELD_VALUE: {
            JitOptRef retval;
            JitOptRef value;
            retval = stack_pointer[-1];
            EMIT_OP_FROM_INST(this_instr);
            value = PyJitRef_StripReferenceInfo(retval);
            ctx->done = true;
            stack_pointer[-1] = value;
            break;
        }

        case _POP_EXCEPT: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_COMMON_CONSTANT: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_BUILD_CLASS: {
            JitOptRef bc;
            EMIT_OP_FROM_INST(this_instr);
            bc = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = bc;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_NAME: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _DELETE_NAME: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _UNPACK_SEQUENCE: {
            JitOptRef *top;
            EMIT_OP_FROM_INST(this_instr);
            top = &stack_pointer[-1 + oparg];
            for (int _i = 0; --_i >= 0;) {
                top[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS(-1 + oparg);
            stack_pointer += -1 + oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _UNPACK_SEQUENCE_TWO_TUPLE: {
            JitOptRef val1;
            JitOptRef val0;
            EMIT_OP_FROM_INST(this_instr);
            val1 = sym_new_not_null(ctx);
            val0 = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = val1;
            stack_pointer[0] = val0;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _UNPACK_SEQUENCE_TUPLE: {
            JitOptRef *values;
            EMIT_OP_FROM_INST(this_instr);
            values = &stack_pointer[-1];
            for (int _i = oparg; --_i >= 0;) {
                values[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS(-1 + oparg);
            stack_pointer += -1 + oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _UNPACK_SEQUENCE_LIST: {
            JitOptRef *values;
            EMIT_OP_FROM_INST(this_instr);
            values = &stack_pointer[-1];
            for (int _i = oparg; --_i >= 0;) {
                values[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS(-1 + oparg);
            stack_pointer += -1 + oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _UNPACK_EX: {
            JitOptRef *top;
            EMIT_OP_FROM_INST(this_instr);
            top = &stack_pointer[(oparg & 0xFF) + (oparg >> 8)];
            for (int _i = 0; --_i >= 0;) {
                top[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS((oparg & 0xFF) + (oparg >> 8));
            stack_pointer += (oparg & 0xFF) + (oparg >> 8);
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_ATTR: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _DELETE_ATTR: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_GLOBAL: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _DELETE_GLOBAL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_LOCALS: {
            JitOptRef locals;
            EMIT_OP_FROM_INST(this_instr);
            locals = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = locals;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        /* _LOAD_FROM_DICT_OR_GLOBALS is not a viable micro-op for tier 2 */

        case _LOAD_NAME: {
            JitOptRef v;
            EMIT_OP_FROM_INST(this_instr);
            v = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = v;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_GLOBAL: {
            JitOptRef *res;
            EMIT_OP_FROM_INST(this_instr);
            res = &stack_pointer[0];
            res[0] = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _PUSH_NULL_CONDITIONAL: {
            JitOptRef *null;
            EMIT_OP_FROM_INST(this_instr);
            null = &stack_pointer[0];
            for (int _i = oparg & 1; --_i >= 0;) {
                null[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS((oparg & 1));
            stack_pointer += (oparg & 1);
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_GLOBALS_VERSION: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_GLOBAL_MODULE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_GLOBAL_BUILTINS: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _DELETE_FAST: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _MAKE_CELL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _DELETE_DEREF: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_FROM_DICT_OR_DEREF: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            break;
        }

        case _LOAD_DEREF: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_DEREF: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _COPY_FREE_VARS: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _BUILD_STRING: {
            JitOptRef str;
            EMIT_OP_FROM_INST(this_instr);
            str = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg);
            stack_pointer[-oparg] = str;
            stack_pointer += 1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_INTERPOLATION: {
            JitOptRef interpolation;
            EMIT_OP_FROM_INST(this_instr);
            interpolation = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - (oparg & 1));
            stack_pointer[-2 - (oparg & 1)] = interpolation;
            stack_pointer += -1 - (oparg & 1);
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_TEMPLATE: {
            JitOptRef template;
            EMIT_OP_FROM_INST(this_instr);
            template = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = template;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_TUPLE: {
            JitOptRef tup;
            EMIT_OP_FROM_INST(this_instr);
            tup = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg);
            stack_pointer[-oparg] = tup;
            stack_pointer += 1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_LIST: {
            JitOptRef list;
            EMIT_OP_FROM_INST(this_instr);
            list = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg);
            stack_pointer[-oparg] = list;
            stack_pointer += 1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LIST_EXTEND: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _SET_UPDATE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_SET: {
            JitOptRef set;
            EMIT_OP_FROM_INST(this_instr);
            set = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg);
            stack_pointer[-oparg] = set;
            stack_pointer += 1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_MAP: {
            JitOptRef map;
            EMIT_OP_FROM_INST(this_instr);
            map = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg*2);
            stack_pointer[-oparg*2] = map;
            stack_pointer += 1 - oparg*2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _SETUP_ANNOTATIONS: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _DICT_UPDATE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _DICT_MERGE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MAP_ADD: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_SUPER_ATTR_ATTR: {
            JitOptRef attr_st;
            EMIT_OP_FROM_INST(this_instr);
            attr_st = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = attr_st;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_SUPER_ATTR_METHOD: {
            JitOptRef attr;
            JitOptRef self_or_null;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            self_or_null = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-3] = attr;
            stack_pointer[-2] = self_or_null;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_ATTR: {
            JitOptRef attr;
            JitOptRef *self_or_null;
            EMIT_OP_FROM_INST(this_instr);
            self_or_null = &stack_pointer[0];
            attr = sym_new_not_null(ctx);
            for (int _i = oparg&1; --_i >= 0;) {
                self_or_null[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS((oparg&1));
            stack_pointer[-1] = attr;
            stack_pointer += (oparg&1);
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_TYPE_VERSION: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_TYPE_VERSION_AND_LOCK: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_MANAGED_OBJECT_HAS_VALUES: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_ATTR_INSTANCE_VALUE: {
            JitOptRef attr;
            JitOptRef o;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            o = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = attr;
            stack_pointer[0] = o;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_ATTR_MODULE: {
            JitOptRef attr;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            break;
        }

        case _LOAD_ATTR_WITH_HINT: {
            JitOptRef attr;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            break;
        }

        case _LOAD_ATTR_SLOT: {
            JitOptRef attr;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            break;
        }

        case _CHECK_ATTR_CLASS: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_ATTR_CLASS: {
            JitOptRef attr;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            break;
        }

        case _LOAD_ATTR_PROPERTY_FRAME: {
            JitOptRef new_frame;
            EMIT_OP_FROM_INST(this_instr);
            new_frame = sym_new_not_null(ctx);
            stack_pointer[-1] = new_frame;
            break;
        }

        /* _LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN is not a viable micro-op for tier 2 */

        case _GUARD_DORV_NO_DICT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _STORE_ATTR_INSTANCE_VALUE: {
            JitOptRef o;
            EMIT_OP_FROM_INST(this_instr);
            o = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = o;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_ATTR_WITH_HINT: {
            JitOptRef o;
            EMIT_OP_FROM_INST(this_instr);
            o = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = o;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _STORE_ATTR_SLOT: {
            JitOptRef o;
            EMIT_OP_FROM_INST(this_instr);
            o = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = o;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _COMPARE_OP: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _COMPARE_OP_FLOAT: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _COMPARE_OP_INT: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _COMPARE_OP_STR: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _IS_OP: {
            JitOptRef b;
            EMIT_OP_FROM_INST(this_instr);
            b = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CONTAINS_OP: {
            JitOptRef b;
            EMIT_OP_FROM_INST(this_instr);
            b = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_TOS_ANY_SET: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CONTAINS_OP_SET: {
            JitOptRef b;
            EMIT_OP_FROM_INST(this_instr);
            b = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CONTAINS_OP_DICT: {
            JitOptRef b;
            EMIT_OP_FROM_INST(this_instr);
            b = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CHECK_EG_MATCH: {
            JitOptRef rest;
            JitOptRef match;
            EMIT_OP_FROM_INST(this_instr);
            rest = sym_new_not_null(ctx);
            match = sym_new_not_null(ctx);
            stack_pointer[-2] = rest;
            stack_pointer[-1] = match;
            break;
        }

        case _CHECK_EXC_MATCH: {
            JitOptRef b;
            EMIT_OP_FROM_INST(this_instr);
            b = sym_new_not_null(ctx);
            stack_pointer[-1] = b;
            break;
        }

        case _IMPORT_NAME: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _IMPORT_FROM: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        /* _POP_JUMP_IF_FALSE is not a viable micro-op for tier 2 */

        /* _POP_JUMP_IF_TRUE is not a viable micro-op for tier 2 */

        case _IS_NONE: {
            JitOptRef b;
            EMIT_OP_FROM_INST(this_instr);
            b = sym_new_not_null(ctx);
            stack_pointer[-1] = b;
            break;
        }

        /* _JUMP_BACKWARD_NO_INTERRUPT is not a viable micro-op for tier 2 */

        case _GET_LEN: {
            JitOptRef len;
            EMIT_OP_FROM_INST(this_instr);
            len = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = len;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MATCH_CLASS: {
            JitOptRef attrs;
            EMIT_OP_FROM_INST(this_instr);
            attrs = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = attrs;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MATCH_MAPPING: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MATCH_SEQUENCE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MATCH_KEYS: {
            JitOptRef values_or_none;
            EMIT_OP_FROM_INST(this_instr);
            values_or_none = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = values_or_none;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GET_ITER: {
            JitOptRef iter;
            JitOptRef index_or_null;
            EMIT_OP_FROM_INST(this_instr);
            iter = sym_new_not_null(ctx);
            index_or_null = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = iter;
            stack_pointer[0] = index_or_null;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GET_YIELD_FROM_ITER: {
            JitOptRef iter;
            EMIT_OP_FROM_INST(this_instr);
            iter = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            break;
        }

        /* _FOR_ITER is not a viable micro-op for tier 2 */

        case _FOR_ITER_TIER_TWO: {
            JitOptRef next;
            EMIT_OP_FROM_INST(this_instr);
            next = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = next;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        /* _INSTRUMENTED_FOR_ITER is not a viable micro-op for tier 2 */

        case _ITER_CHECK_LIST: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _ITER_JUMP_LIST is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_LIST: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _ITER_NEXT_LIST is not a viable micro-op for tier 2 */

        case _ITER_NEXT_LIST_TIER_TWO: {
            JitOptRef next;
            EMIT_OP_FROM_INST(this_instr);
            next = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = next;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _ITER_CHECK_TUPLE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _ITER_JUMP_TUPLE is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_TUPLE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _ITER_NEXT_TUPLE: {
            JitOptRef next;
            EMIT_OP_FROM_INST(this_instr);
            next = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = next;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _ITER_CHECK_RANGE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _ITER_JUMP_RANGE is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_RANGE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _ITER_NEXT_RANGE: {
            JitOptRef next;
            EMIT_OP_FROM_INST(this_instr);
            next = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = next;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _FOR_ITER_GEN_FRAME: {
            JitOptRef iter;
            JitOptRef gen_frame;
            EMIT_OP_FROM_INST(this_instr);
            gen_frame = PyJitRef_NULL;
            ctx->done = true;
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = gen_frame;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _INSERT_NULL: {
            JitOptRef *method_and_self;
            EMIT_OP_FROM_INST(this_instr);
            method_and_self = &stack_pointer[-1];
            for (int _i = 2; --_i >= 0;) {
                method_and_self[_i] = sym_new_not_null(ctx);
            }
            CHECK_STACK_BOUNDS(1);
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_SPECIAL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _WITH_EXCEPT_START: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _PUSH_EXC_INFO: {
            JitOptRef prev_exc;
            JitOptRef new_exc;
            EMIT_OP_FROM_INST(this_instr);
            prev_exc = sym_new_not_null(ctx);
            new_exc = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = prev_exc;
            stack_pointer[0] = new_exc;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_DORV_VALUES_INST_ATTR_FROM_DICT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_KEYS_VERSION: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_ATTR_METHOD_WITH_VALUES: {
            JitOptRef attr;
            JitOptRef self;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            self = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = attr;
            stack_pointer[0] = self;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_ATTR_METHOD_NO_DICT: {
            JitOptRef attr;
            JitOptRef self;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            self = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = attr;
            stack_pointer[0] = self;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES: {
            JitOptRef attr;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            break;
        }

        case _LOAD_ATTR_NONDESCRIPTOR_NO_DICT: {
            JitOptRef attr;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            break;
        }

        case _CHECK_ATTR_METHOD_LAZY_DICT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_ATTR_METHOD_LAZY_DICT: {
            JitOptRef attr;
            JitOptRef self;
            EMIT_OP_FROM_INST(this_instr);
            attr = sym_new_not_null(ctx);
            self = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = attr;
            stack_pointer[0] = self;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MAYBE_EXPAND_METHOD: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _DO_CALL is not a viable micro-op for tier 2 */

        /* _MONITOR_CALL is not a viable micro-op for tier 2 */

        case _PY_FRAME_GENERAL: {
            JitOptRef new_frame;
            EMIT_OP_FROM_INST(this_instr);
            new_frame = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = new_frame;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CHECK_FUNCTION_VERSION: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_FUNCTION_VERSION_INLINE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_METHOD_VERSION: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _EXPAND_METHOD: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_IS_NOT_PY_CALLABLE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_NON_PY_GENERAL: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CHECK_CALL_BOUND_METHOD_EXACT_ARGS: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _INIT_CALL_BOUND_METHOD_EXACT_ARGS: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_PEP_523: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_FUNCTION_EXACT_ARGS: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_STACK_SPACE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_RECURSION_REMAINING: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _INIT_CALL_PY_EXACT_ARGS: {
            JitOptRef new_frame;
            EMIT_OP_FROM_INST(this_instr);
            new_frame = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = new_frame;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _PUSH_FRAME: {
            JitOptRef new_frame;
            new_frame = stack_pointer[-1];
            EMIT_OP_FROM_INST(this_instr);
            new_frame = sym_new_unknown(ctx);
            ctx->done = true;
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_NOS_NULL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_NOS_NOT_NULL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_THIRD_NULL: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_CALLABLE_TYPE_1: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_TYPE_1: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_CALLABLE_STR_1: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_STR_1: {
            JitOptRef res;
            JitOptRef a;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            a = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-3] = res;
            stack_pointer[-2] = a;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_CALLABLE_TUPLE_1: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_TUPLE_1: {
            JitOptRef res;
            JitOptRef a;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            a = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-3] = res;
            stack_pointer[-2] = a;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CHECK_AND_ALLOCATE_OBJECT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CREATE_INIT_FRAME: {
            JitOptRef *args;
            JitOptRef self;
            JitOptRef init;
            JitOptRef init_frame;
            EMIT_OP_FROM_INST(this_instr);
            ctx->done = true;
            init_frame = PyJitRef_NULL;
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = init_frame;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _EXIT_INIT_CHECK: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_BUILTIN_CLASS: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_BUILTIN_O: {
            JitOptRef res;
            JitOptRef a;
            JitOptRef c;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            a = sym_new_not_null(ctx);
            c = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer[-1 - oparg] = a;
            stack_pointer[-oparg] = c;
            stack_pointer += 1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_BUILTIN_FAST: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_BUILTIN_FAST_WITH_KEYWORDS: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_CALLABLE_LEN: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_LEN: {
            JitOptRef res;
            JitOptRef a;
            JitOptRef c;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            a = sym_new_not_null(ctx);
            c = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer[-2] = a;
            stack_pointer[-1] = c;
            break;
        }

        case _GUARD_CALLABLE_ISINSTANCE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_ISINSTANCE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-3);
            stack_pointer[-4] = res;
            stack_pointer += -3;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_CALLABLE_LIST_APPEND: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_LIST_APPEND: {
            JitOptRef c;
            JitOptRef s;
            EMIT_OP_FROM_INST(this_instr);
            c = sym_new_not_null(ctx);
            s = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-3] = c;
            stack_pointer[-2] = s;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_O: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_NOARGS: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_FAST: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1 - oparg);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        /* _MONITOR_CALL_KW is not a viable micro-op for tier 2 */

        case _MAYBE_EXPAND_METHOD_KW: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _DO_CALL_KW is not a viable micro-op for tier 2 */

        case _PY_FRAME_KW: {
            JitOptRef new_frame;
            EMIT_OP_FROM_INST(this_instr);
            new_frame = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2 - oparg);
            stack_pointer[-3 - oparg] = new_frame;
            stack_pointer += -2 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CHECK_FUNCTION_VERSION_KW: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_METHOD_VERSION_KW: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _EXPAND_METHOD_KW: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_IS_NOT_PY_CALLABLE_KW: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CALL_KW_NON_PY: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2 - oparg);
            stack_pointer[-3 - oparg] = res;
            stack_pointer += -2 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _MAKE_CALLARGS_A_TUPLE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _DO_CALL_FUNCTION_EX is not a viable micro-op for tier 2 */

        case _MAKE_FUNCTION: {
            JitOptRef func;
            EMIT_OP_FROM_INST(this_instr);
            func = sym_new_not_null(ctx);
            stack_pointer[-1] = func;
            break;
        }

        case _SET_FUNCTION_ATTRIBUTE: {
            JitOptRef func_out;
            EMIT_OP_FROM_INST(this_instr);
            func_out = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = func_out;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _RETURN_GENERATOR: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_unknown(ctx);
            ctx->done = true;
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = res;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BUILD_SLICE: {
            JitOptRef slice;
            EMIT_OP_FROM_INST(this_instr);
            slice = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1 - oparg);
            stack_pointer[-oparg] = slice;
            stack_pointer += 1 - oparg;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _CONVERT_VALUE: {
            JitOptRef result;
            EMIT_OP_FROM_INST(this_instr);
            result = sym_new_not_null(ctx);
            stack_pointer[-1] = result;
            break;
        }

        case _FORMAT_SIMPLE: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            break;
        }

        case _FORMAT_WITH_SPEC: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _COPY: {
            JitOptRef top;
            EMIT_OP_FROM_INST(this_instr);
            top = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = top;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP: {
            JitOptRef res;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _SWAP: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        /* _INSTRUMENTED_LINE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_INSTRUCTION is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_JUMP_FORWARD is not a viable micro-op for tier 2 */

        /* _MONITOR_JUMP_BACKWARD is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_NOT_TAKEN is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_TRUE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_FALSE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_NONE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_NOT_NONE is not a viable micro-op for tier 2 */

        case _GUARD_IS_TRUE_POP: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_IS_FALSE_POP: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_IS_NONE_POP: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _GUARD_IS_NOT_NONE_POP: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _JUMP_TO_TOP: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _SET_IP: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_STACK_SPACE_OPERAND: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _SAVE_RETURN_OFFSET: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _EXIT_TRACE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _DYNAMIC_EXIT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _CHECK_VALIDITY: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _LOAD_CONST_INLINE: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP_LOAD_CONST_INLINE: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            break;
        }

        case _LOAD_CONST_INLINE_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[0] = value;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_CALL: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_CALL_ONE: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-3);
            stack_pointer += -3;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_CALL_TWO: {
            EMIT_OP_FROM_INST(this_instr);
            CHECK_STACK_BOUNDS(-4);
            stack_pointer += -4;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_TOP_LOAD_CONST_INLINE_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            break;
        }

        case _POP_TWO_LOAD_CONST_INLINE_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = value;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_CALL_LOAD_CONST_INLINE_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-1);
            stack_pointer[-2] = value;
            stack_pointer += -1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _POP_CALL_ONE_LOAD_CONST_INLINE_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-2);
            stack_pointer[-3] = value;
            stack_pointer += -2;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _SHUFFLE_3_LOAD_CONST_INLINE_BORROW: {
            JitOptRef res;
            JitOptRef a;
            JitOptRef c;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            a = sym_new_not_null(ctx);
            c = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer[-2] = a;
            stack_pointer[-1] = c;
            break;
        }

        case _POP_CALL_TWO_LOAD_CONST_INLINE_BORROW: {
            JitOptRef value;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(-3);
            stack_pointer[-4] = value;
            stack_pointer += -3;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_CONST_UNDER_INLINE: {
            JitOptRef value;
            JitOptRef new;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            new = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = value;
            stack_pointer[0] = new;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _LOAD_CONST_UNDER_INLINE_BORROW: {
            JitOptRef value;
            JitOptRef new;
            EMIT_OP_FROM_INST(this_instr);
            value = sym_new_not_null(ctx);
            new = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-1] = value;
            stack_pointer[0] = new;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _START_EXECUTOR: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _MAKE_WARM: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _FATAL_ERROR: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _DEOPT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _HANDLE_PENDING_AND_DEOPT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _ERROR_POP_N: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _SPILL_OR_RELOAD: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _TIER2_RESUME_CHECK: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _COLD_EXIT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _COLD_DYNAMIC_EXIT: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_IP__PUSH_FRAME: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_IP_YIELD_VALUE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_IP_RETURN_VALUE: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _GUARD_IP_RETURN_GENERATOR: {
            EMIT_OP_FROM_INST(this_instr);
            break;
        }

        case _THIRD_TO_FLOAT: {
            JitOptRef st;
            JitOptRef nos2;
            JitOptRef tos2;
            EMIT_OP_FROM_INST(this_instr);
            st = sym_new_not_null(ctx);
            nos2 = sym_new_not_null(ctx);
            tos2 = sym_new_not_null(ctx);
            stack_pointer[-3] = st;
            stack_pointer[-2] = nos2;
            stack_pointer[-1] = tos2;
            break;
        }

        case _TOS_TO_TAGGED_DOUBLE: {
            JitOptRef dbl;
            EMIT_OP_FROM_INST(this_instr);
            dbl = sym_new_not_null(ctx);
            stack_pointer[-1] = dbl;
            break;
        }

        case _NOS_TO_TAGGED_DOUBLE: {
            JitOptRef dbl;
            JitOptRef tos2;
            EMIT_OP_FROM_INST(this_instr);
            dbl = sym_new_not_null(ctx);
            tos2 = sym_new_not_null(ctx);
            stack_pointer[-2] = dbl;
            stack_pointer[-1] = tos2;
            break;
        }

        case _THIRD_TO_TAGGED_DOUBLE: {
            JitOptRef dbl;
            JitOptRef nos2;
            JitOptRef tos2;
            EMIT_OP_FROM_INST(this_instr);
            dbl = sym_new_not_null(ctx);
            nos2 = sym_new_not_null(ctx);
            tos2 = sym_new_not_null(ctx);
            stack_pointer[-3] = dbl;
            stack_pointer[-2] = nos2;
            stack_pointer[-1] = tos2;
            break;
        }

        case _BINARY_OP_MULTIPLY_TAGGED_DOUBLE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_ADD_TAGGED_DOUBLE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBTRACT_TAGGED_DOUBLE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_MULTIPLY_FLOAT_OUT_TAGGED_DOUBLE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_ADD_FLOAT_OUT_TAGGED_DOUBLE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        case _BINARY_OP_SUBTRACT_FLOAT_OUT_TAGGED_DOUBLE: {
            JitOptRef res;
            JitOptRef l;
            JitOptRef r;
            EMIT_OP_FROM_INST(this_instr);
            res = sym_new_not_null(ctx);
            l = sym_new_not_null(ctx);
            r = sym_new_not_null(ctx);
            CHECK_STACK_BOUNDS(1);
            stack_pointer[-2] = res;
            stack_pointer[-1] = l;
            stack_pointer[0] = r;
            stack_pointer += 1;
            ASSERT_WITHIN_STACK_BOUNDS(__FILE__, __LINE__);
            break;
        }

        /* _TRACE_RECORD is not a viable micro-op for tier 2 */

