// This file is generated by Tools/cases_generator/partial_evaluator_generator.py
// from:
//   Python/partial_evaluator_bytecodes.c
// Do not edit!

        case _NOP: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_PERIODIC: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _CHECK_PERIODIC_AT_END is not a viable micro-op for tier 2 */

        case _CHECK_PERIODIC_IF_NOT_YIELD_FROM: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _QUICKEN_RESUME is not a viable micro-op for tier 2 */

        /* _LOAD_BYTECODE is not a viable micro-op for tier 2 */

        case _RESUME_CHECK: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _MONITOR_RESUME is not a viable micro-op for tier 2 */

        case _LOAD_FAST_CHECK: {
            JitOptPESymbol *value;
            COPY_TO_TRACE(this_instr);
            value = GETLOCAL(oparg);
            if (sym_is_null(value)) {
                ctx->done = true;
            }
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _LOAD_FAST: {
            JitOptPESymbol *value;
            COPY_TO_TRACE(this_instr);
            value = GETLOCAL(oparg);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _LOAD_FAST_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_FAST_AND_CLEAR: {
            JitOptPESymbol *value;
            COPY_TO_TRACE(this_instr);
            value = GETLOCAL(oparg);
            GETLOCAL(oparg) = sym_new_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _LOAD_CONST: {
            JitOptPESymbol *value;
            Py_UNREACHABLE();
            value = NULL;
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _LOAD_SMALL_INT: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_FAST: {
            JitOptPESymbol *value;
            value = stack_pointer[-1];
            COPY_TO_TRACE(this_instr);
            GETLOCAL(oparg) = value;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _POP_TOP: {
            COPY_TO_TRACE(this_instr);
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _POP_TOP_NOP: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TOP_INT: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TOP_FLOAT: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TOP_UNICODE: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TWO: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _PUSH_NULL: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _END_FOR: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_ITER: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _END_SEND: {
            JitOptPESymbol *val;
            val = sym_new_not_null(ctx);
            stack_pointer[-2] = val;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNARY_NEGATIVE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNARY_NOT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TO_BOOL: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TO_BOOL_BOOL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TO_BOOL_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_LIST: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_LIST: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_SLICE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TO_BOOL_LIST: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TO_BOOL_NONE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_UNICODE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_UNICODE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TO_BOOL_STR: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _REPLACE_WITH_TRUE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNARY_INVERT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_INT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_INT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_OVERFLOWED: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_OVERFLOWED: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_MULTIPLY_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_ADD_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBTRACT_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_FLOAT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_FLOAT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_MULTIPLY_FLOAT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_ADD_FLOAT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBTRACT_FLOAT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_MULTIPLY_FLOAT__NO_DECREF_INPUTS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_ADD_FLOAT__NO_DECREF_INPUTS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBTRACT_FLOAT__NO_DECREF_INPUTS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_ADD_UNICODE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_INPLACE_ADD_UNICODE: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_BINARY_OP_EXTEND: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_EXTEND: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_SLICE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_SLICE: {
            stack_pointer += -4;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_LIST_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_LIST_SLICE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_STR_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_TUPLE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_TUPLE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_TUPLE_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_DICT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_DICT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_DICT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_CHECK_FUNC: {
            JitOptPESymbol *getitem;
            getitem = sym_new_not_null(ctx);
            stack_pointer[0] = getitem;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP_SUBSCR_INIT_CALL: {
            JitOptPESymbol *new_frame;
            COPY_TO_TRACE(this_instr);
            new_frame = NULL;
            ctx->done = true;
            stack_pointer[-3] = new_frame;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _LIST_APPEND: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _SET_ADD: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_SUBSCR: {
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_SUBSCR_LIST_INT: {
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_SUBSCR_DICT: {
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DELETE_SUBSCR: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_INTRINSIC_1: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_INTRINSIC_2: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _RETURN_VALUE: {
            JitOptPESymbol *retval;
            JitOptPESymbol *res;
            retval = stack_pointer[-1];
            COPY_TO_TRACE(this_instr);
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            ctx->frame->stack_pointer = stack_pointer;
            frame_pop(ctx);
            stack_pointer = ctx->frame->stack_pointer;
            res = retval;
            assert(corresponding_check_stack == NULL);
            assert(co != NULL);
            int framesize = co->co_framesize;
            assert(framesize > 0);
            assert(framesize <= curr_space);
            curr_space -= framesize;
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            co = get_code(this_instr);
            if (co == NULL) {
                ctx->done = true;
            }
            break;
        }

        case _GET_AITER: {
            JitOptPESymbol *iter;
            iter = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GET_ANEXT: {
            JitOptPESymbol *awaitable;
            awaitable = sym_new_not_null(ctx);
            stack_pointer[0] = awaitable;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GET_AWAITABLE: {
            JitOptPESymbol *iter;
            iter = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _SEND is not a viable micro-op for tier 2 */

        case _SEND_GEN_FRAME: {
            JitOptPESymbol *gen_frame;
            COPY_TO_TRACE(this_instr);
            gen_frame = NULL;
            ctx->done = true;
            stack_pointer[-1] = gen_frame;
            break;
        }

        case _YIELD_VALUE: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_EXCEPT: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_COMMON_CONSTANT: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_BUILD_CLASS: {
            JitOptPESymbol *bc;
            bc = sym_new_not_null(ctx);
            stack_pointer[0] = bc;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_NAME: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DELETE_NAME: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNPACK_SEQUENCE: {
            JitOptPESymbol **values;
            JitOptPESymbol **top;
            values = &stack_pointer[-1];
            top = &stack_pointer[-1 + oparg];
            COPY_TO_TRACE(this_instr);
            (void)top;
            for (int i = 0; i < oparg; i++) {
                values[i] = sym_new_unknown(ctx);
            }
            stack_pointer += -1 + oparg;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _UNPACK_SEQUENCE_TWO_TUPLE: {
            JitOptPESymbol *val1;
            JitOptPESymbol *val0;
            val1 = sym_new_not_null(ctx);
            val0 = sym_new_not_null(ctx);
            stack_pointer[-1] = val1;
            stack_pointer[0] = val0;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNPACK_SEQUENCE_TUPLE: {
            JitOptPESymbol **values;
            values = &stack_pointer[-1];
            for (int _i = oparg; --_i >= 0;) {
                values[_i] = sym_new_not_null(ctx);
            }
            stack_pointer += -1 + oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNPACK_SEQUENCE_LIST: {
            JitOptPESymbol **values;
            values = &stack_pointer[-1];
            for (int _i = oparg; --_i >= 0;) {
                values[_i] = sym_new_not_null(ctx);
            }
            stack_pointer += -1 + oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _UNPACK_EX: {
            JitOptPESymbol **values;
            JitOptPESymbol **top;
            values = &stack_pointer[-1];
            top = &stack_pointer[(oparg & 0xFF) + (oparg >> 8)];
            COPY_TO_TRACE(this_instr);
            (void)top;
            int totalargs = (oparg & 0xFF) + (oparg >> 8) + 1;
            for (int i = 0; i < totalargs; i++) {
                values[i] = sym_new_unknown(ctx);
            }
            stack_pointer += (oparg & 0xFF) + (oparg >> 8);
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _STORE_ATTR: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DELETE_ATTR: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_GLOBAL: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DELETE_GLOBAL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_LOCALS: {
            JitOptPESymbol *locals;
            locals = sym_new_not_null(ctx);
            stack_pointer[0] = locals;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _LOAD_FROM_DICT_OR_GLOBALS is not a viable micro-op for tier 2 */

        case _LOAD_NAME: {
            JitOptPESymbol *v;
            v = sym_new_not_null(ctx);
            stack_pointer[0] = v;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_GLOBAL: {
            JitOptPESymbol **res;
            res = &stack_pointer[0];
            res[0] = sym_new_not_null(ctx);
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _PUSH_NULL_CONDITIONAL: {
            JitOptPESymbol **null;
            null = &stack_pointer[0];
            for (int _i = oparg & 1; --_i >= 0;) {
                null[_i] = sym_new_not_null(ctx);
            }
            stack_pointer += (oparg & 1);
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_GLOBALS_VERSION: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_GLOBAL_MODULE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_GLOBAL_BUILTINS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DELETE_FAST: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MAKE_CELL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DELETE_DEREF: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_FROM_DICT_OR_DEREF: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_DEREF: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_DEREF: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COPY_FREE_VARS: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_STRING: {
            JitOptPESymbol *str;
            str = sym_new_not_null(ctx);
            stack_pointer[-oparg] = str;
            stack_pointer += 1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_INTERPOLATION: {
            JitOptPESymbol *interpolation;
            interpolation = sym_new_not_null(ctx);
            stack_pointer[-2 - (oparg & 1)] = interpolation;
            stack_pointer += -1 - (oparg & 1);
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_TEMPLATE: {
            JitOptPESymbol *template;
            template = sym_new_not_null(ctx);
            stack_pointer[-2] = template;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_TUPLE: {
            JitOptPESymbol *tup;
            tup = sym_new_not_null(ctx);
            stack_pointer[-oparg] = tup;
            stack_pointer += 1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_LIST: {
            JitOptPESymbol *list;
            list = sym_new_not_null(ctx);
            stack_pointer[-oparg] = list;
            stack_pointer += 1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LIST_EXTEND: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _SET_UPDATE: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_SET: {
            JitOptPESymbol *set;
            set = sym_new_not_null(ctx);
            stack_pointer[-oparg] = set;
            stack_pointer += 1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BUILD_MAP: {
            JitOptPESymbol *map;
            map = sym_new_not_null(ctx);
            stack_pointer[-oparg*2] = map;
            stack_pointer += 1 - oparg*2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _SETUP_ANNOTATIONS: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DICT_UPDATE: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DICT_MERGE: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MAP_ADD: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_SUPER_ATTR_ATTR: {
            JitOptPESymbol *attr_st;
            attr_st = sym_new_not_null(ctx);
            stack_pointer[-3] = attr_st;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_SUPER_ATTR_METHOD: {
            JitOptPESymbol *attr;
            JitOptPESymbol *self_or_null;
            attr = sym_new_not_null(ctx);
            self_or_null = sym_new_not_null(ctx);
            stack_pointer[-3] = attr;
            stack_pointer[-2] = self_or_null;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR: {
            JitOptPESymbol **attr;
            JitOptPESymbol **self_or_null;
            attr = &stack_pointer[-1];
            self_or_null = &stack_pointer[0];
            attr[0] = sym_new_not_null(ctx);
            for (int _i = oparg&1; --_i >= 0;) {
                self_or_null[_i] = sym_new_not_null(ctx);
            }
            stack_pointer += (oparg&1);
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TYPE_VERSION: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TYPE_VERSION_AND_LOCK: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_MANAGED_OBJECT_HAS_VALUES: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_INSTANCE_VALUE: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_MODULE: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_WITH_HINT: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_SLOT: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_ATTR_CLASS: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_CLASS: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_PROPERTY_FRAME: {
            JitOptPESymbol *new_frame;
            PyObject *fget = (PyObject *)this_instr->operand0;
            COPY_TO_TRACE(this_instr);
            new_frame = NULL;
            ctx->done = true;
            stack_pointer[-1] = new_frame;
            break;
        }

        /* _LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN is not a viable micro-op for tier 2 */

        case _GUARD_DORV_NO_DICT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_ATTR_INSTANCE_VALUE: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_ATTR_WITH_HINT: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _STORE_ATTR_SLOT: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COMPARE_OP: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COMPARE_OP_FLOAT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COMPARE_OP_INT: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COMPARE_OP_STR: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _IS_OP: {
            JitOptPESymbol *b;
            b = sym_new_not_null(ctx);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CONTAINS_OP: {
            JitOptPESymbol *b;
            b = sym_new_not_null(ctx);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_TOS_ANY_SET: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CONTAINS_OP_SET: {
            JitOptPESymbol *b;
            b = sym_new_not_null(ctx);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CONTAINS_OP_DICT: {
            JitOptPESymbol *b;
            b = sym_new_not_null(ctx);
            stack_pointer[-2] = b;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_EG_MATCH: {
            JitOptPESymbol *rest;
            JitOptPESymbol *match;
            rest = sym_new_not_null(ctx);
            match = sym_new_not_null(ctx);
            stack_pointer[-2] = rest;
            stack_pointer[-1] = match;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_EXC_MATCH: {
            JitOptPESymbol *b;
            b = sym_new_not_null(ctx);
            stack_pointer[-1] = b;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _IMPORT_NAME: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _IMPORT_FROM: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _POP_JUMP_IF_FALSE is not a viable micro-op for tier 2 */

        /* _POP_JUMP_IF_TRUE is not a viable micro-op for tier 2 */

        case _IS_NONE: {
            JitOptPESymbol *b;
            b = sym_new_not_null(ctx);
            stack_pointer[-1] = b;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GET_LEN: {
            JitOptPESymbol *len;
            len = sym_new_not_null(ctx);
            stack_pointer[0] = len;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MATCH_CLASS: {
            JitOptPESymbol *attrs;
            attrs = sym_new_not_null(ctx);
            stack_pointer[-3] = attrs;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MATCH_MAPPING: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MATCH_SEQUENCE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MATCH_KEYS: {
            JitOptPESymbol *values_or_none;
            values_or_none = sym_new_not_null(ctx);
            stack_pointer[0] = values_or_none;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GET_ITER: {
            JitOptPESymbol *iter;
            JitOptPESymbol *index_or_null;
            iter = sym_new_not_null(ctx);
            index_or_null = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            stack_pointer[0] = index_or_null;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GET_YIELD_FROM_ITER: {
            JitOptPESymbol *iter;
            iter = sym_new_not_null(ctx);
            stack_pointer[-1] = iter;
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _FOR_ITER is not a viable micro-op for tier 2 */

        case _FOR_ITER_TIER_TWO: {
            JitOptPESymbol *next;
            next = sym_new_not_null(ctx);
            stack_pointer[0] = next;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _INSTRUMENTED_FOR_ITER is not a viable micro-op for tier 2 */

        case _ITER_CHECK_LIST: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _ITER_JUMP_LIST is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_LIST: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _ITER_NEXT_LIST is not a viable micro-op for tier 2 */

        case _ITER_NEXT_LIST_TIER_TWO: {
            JitOptPESymbol *next;
            next = sym_new_not_null(ctx);
            stack_pointer[0] = next;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _ITER_CHECK_TUPLE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _ITER_JUMP_TUPLE is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_TUPLE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _ITER_NEXT_TUPLE: {
            JitOptPESymbol *next;
            next = sym_new_not_null(ctx);
            stack_pointer[0] = next;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _ITER_CHECK_RANGE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _ITER_JUMP_RANGE is not a viable micro-op for tier 2 */

        case _GUARD_NOT_EXHAUSTED_RANGE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _ITER_NEXT_RANGE: {
            JitOptPESymbol *next;
            next = sym_new_not_null(ctx);
            stack_pointer[0] = next;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _FOR_ITER_GEN_FRAME: {
            JitOptPESymbol *gen_frame;
            COPY_TO_TRACE(this_instr);
            gen_frame = NULL;
            ctx->done = true;
            stack_pointer[0] = gen_frame;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _INSERT_NULL: {
            JitOptPESymbol **method_and_self;
            method_and_self = &stack_pointer[-1];
            for (int _i = 2; --_i >= 0;) {
                method_and_self[_i] = sym_new_not_null(ctx);
            }
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_SPECIAL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _WITH_EXCEPT_START: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _PUSH_EXC_INFO: {
            JitOptPESymbol *prev_exc;
            JitOptPESymbol *new_exc;
            prev_exc = sym_new_not_null(ctx);
            new_exc = sym_new_not_null(ctx);
            stack_pointer[-1] = prev_exc;
            stack_pointer[0] = new_exc;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_DORV_VALUES_INST_ATTR_FROM_DICT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_KEYS_VERSION: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_METHOD_WITH_VALUES: {
            JitOptPESymbol *attr;
            JitOptPESymbol *self;
            attr = sym_new_not_null(ctx);
            self = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            stack_pointer[0] = self;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_METHOD_NO_DICT: {
            JitOptPESymbol *attr;
            JitOptPESymbol *self;
            attr = sym_new_not_null(ctx);
            self = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            stack_pointer[0] = self;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_NONDESCRIPTOR_WITH_VALUES: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_NONDESCRIPTOR_NO_DICT: {
            JitOptPESymbol *attr;
            attr = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_ATTR_METHOD_LAZY_DICT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_ATTR_METHOD_LAZY_DICT: {
            JitOptPESymbol *attr;
            JitOptPESymbol *self;
            attr = sym_new_not_null(ctx);
            self = sym_new_not_null(ctx);
            stack_pointer[-1] = attr;
            stack_pointer[0] = self;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MAYBE_EXPAND_METHOD: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _DO_CALL is not a viable micro-op for tier 2 */

        /* _MONITOR_CALL is not a viable micro-op for tier 2 */

        case _PY_FRAME_GENERAL: {
            JitOptPESymbol *new_frame;
            COPY_TO_TRACE(this_instr);
            PyCodeObject *co = NULL;
            assert((this_instr + 2)->opcode == _PUSH_FRAME);
            co = get_code_with_logging((this_instr + 2));
            if (co == NULL) {
                ctx->done = true;
                break;
            }
            new_frame = (JitOptPESymbol *)frame_new(ctx, co, 0, NULL, 0);
            stack_pointer[-2 - oparg] = new_frame;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _CHECK_FUNCTION_VERSION: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_FUNCTION_VERSION_INLINE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_METHOD_VERSION: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _EXPAND_METHOD: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_IS_NOT_PY_CALLABLE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_NON_PY_GENERAL: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_CALL_BOUND_METHOD_EXACT_ARGS: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _INIT_CALL_BOUND_METHOD_EXACT_ARGS: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_PEP_523: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_FUNCTION_EXACT_ARGS: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_STACK_SPACE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_RECURSION_REMAINING: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _INIT_CALL_PY_EXACT_ARGS: {
            JitOptPESymbol **args;
            JitOptPESymbol *self_or_null;
            JitOptPESymbol *new_frame;
            args = &stack_pointer[-oparg];
            self_or_null = stack_pointer[-1 - oparg];
            COPY_TO_TRACE(this_instr);
            int argcount = oparg;
            PyCodeObject *co = NULL;
            assert((this_instr + 2)->opcode == _PUSH_FRAME);
            co = get_code_with_logging((this_instr + 2));
            if (co == NULL) {
                ctx->done = true;
                break;
            }
            assert(self_or_null != NULL);
            assert(args != NULL);
            if (sym_is_not_null(self_or_null)) {
                args--;
                argcount++;
            }
            if (sym_is_null(self_or_null) || sym_is_not_null(self_or_null)) {
                new_frame = (JitOptPESymbol *)frame_new(ctx, co, 0, args, argcount);
            } else {
                new_frame = (JitOptPESymbol *)frame_new(ctx, co, 0, NULL, 0);
            }
            stack_pointer[-2 - oparg] = new_frame;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _PUSH_FRAME: {
            JitOptPESymbol *new_frame;
            new_frame = stack_pointer[-1];
            COPY_TO_TRACE(this_instr);
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            ctx->frame->stack_pointer = stack_pointer;
            ctx->frame = (_Py_UOpsPEAbstractFrame *)new_frame;
            ctx->curr_frame_depth++;
            stack_pointer = ((_Py_UOpsPEAbstractFrame *)new_frame)->stack_pointer;
            co = get_code(this_instr);
            if (co == NULL) {
                ctx->done = true;
                break;
            }
            int framesize = co->co_framesize;
            assert(framesize > 0);
            curr_space += framesize;
            if (curr_space < 0 || curr_space > INT32_MAX) {
                ctx->done = true;
                break;
            }
            max_space = curr_space > max_space ? curr_space : max_space;
            if (first_valid_check_stack == NULL) {
                first_valid_check_stack = corresponding_check_stack;
            }
            else if (corresponding_check_stack) {
                corresponding_check_stack->opcode = _NOP;
            }
            corresponding_check_stack = NULL;
            break;
        }

        case _GUARD_NOS_NULL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_NOS_NOT_NULL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_THIRD_NULL: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_CALLABLE_TYPE_1: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_TYPE_1: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_CALLABLE_STR_1: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_STR_1: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_CALLABLE_TUPLE_1: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_TUPLE_1: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_AND_ALLOCATE_OBJECT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CREATE_INIT_FRAME: {
            JitOptPESymbol *init_frame;
            COPY_TO_TRACE(this_instr);
            init_frame = NULL;
            ctx->done = true;
            stack_pointer[-2 - oparg] = init_frame;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _EXIT_INIT_CHECK: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_BUILTIN_CLASS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_BUILTIN_O: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_BUILTIN_FAST: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_BUILTIN_FAST_WITH_KEYWORDS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_CALLABLE_LEN: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_LEN: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-3] = res;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_CALLABLE_ISINSTANCE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_ISINSTANCE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-4] = res;
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_CALLABLE_LIST_APPEND: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_LIST_APPEND: {
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_O: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_NOARGS: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_METHOD_DESCRIPTOR_FAST: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2 - oparg] = res;
            stack_pointer += -1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _MONITOR_CALL_KW is not a viable micro-op for tier 2 */

        case _MAYBE_EXPAND_METHOD_KW: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _DO_CALL_KW is not a viable micro-op for tier 2 */

        case _PY_FRAME_KW: {
            JitOptPESymbol *new_frame;
            COPY_TO_TRACE(this_instr);
            new_frame = NULL;
            ctx->done = true;
            stack_pointer[-3 - oparg] = new_frame;
            stack_pointer += -2 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            break;
        }

        case _CHECK_FUNCTION_VERSION_KW: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_METHOD_VERSION_KW: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _EXPAND_METHOD_KW: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_IS_NOT_PY_CALLABLE_KW: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CALL_KW_NON_PY: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-3 - oparg] = res;
            stack_pointer += -2 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MAKE_CALLARGS_A_TUPLE: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _DO_CALL_FUNCTION_EX is not a viable micro-op for tier 2 */

        case _MAKE_FUNCTION: {
            JitOptPESymbol *func;
            func = sym_new_not_null(ctx);
            stack_pointer[-1] = func;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _SET_FUNCTION_ATTRIBUTE: {
            JitOptPESymbol *func_out;
            func_out = sym_new_not_null(ctx);
            stack_pointer[-2] = func_out;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _RETURN_GENERATOR: {
            JitOptPESymbol *res;
            COPY_TO_TRACE(this_instr);
            ctx->frame->stack_pointer = stack_pointer;
            frame_pop(ctx);
            stack_pointer = ctx->frame->stack_pointer;
            res = sym_new_unknown(ctx);
            assert(corresponding_check_stack == NULL);
            assert(co != NULL);
            int framesize = co->co_framesize;
            assert(framesize > 0);
            assert(framesize <= curr_space);
            curr_space -= framesize;
            stack_pointer[0] = res;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            co = get_code(this_instr);
            if (co == NULL) {
                ctx->done = true;
            }
            break;
        }

        case _BUILD_SLICE: {
            JitOptPESymbol *slice;
            slice = sym_new_not_null(ctx);
            stack_pointer[-oparg] = slice;
            stack_pointer += 1 - oparg;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CONVERT_VALUE: {
            JitOptPESymbol *result;
            result = sym_new_not_null(ctx);
            stack_pointer[-1] = result;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _FORMAT_SIMPLE: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-1] = res;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _FORMAT_WITH_SPEC: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COPY: {
            JitOptPESymbol *top;
            top = sym_new_not_null(ctx);
            stack_pointer[0] = top;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _BINARY_OP: {
            JitOptPESymbol *res;
            res = sym_new_not_null(ctx);
            stack_pointer[-2] = res;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _SWAP: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        /* _INSTRUMENTED_LINE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_INSTRUCTION is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_JUMP_FORWARD is not a viable micro-op for tier 2 */

        /* _MONITOR_JUMP_BACKWARD is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_NOT_TAKEN is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_TRUE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_FALSE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_NONE is not a viable micro-op for tier 2 */

        /* _INSTRUMENTED_POP_JUMP_IF_NOT_NONE is not a viable micro-op for tier 2 */

        case _GUARD_IS_TRUE_POP: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_IS_FALSE_POP: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_IS_NONE_POP: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _GUARD_IS_NOT_NONE_POP: {
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _JUMP_TO_TOP: {
            COPY_TO_TRACE(this_instr);
            ctx->done = true;
            break;
        }

        case _SET_IP: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_STACK_SPACE_OPERAND: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _SAVE_RETURN_OFFSET: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _EXIT_TRACE: {
            PyObject *exit_p = (PyObject *)this_instr->operand0;
            COPY_TO_TRACE(this_instr);
            (void)exit_p;
            ctx->done = true;
            break;
        }

        case _CHECK_VALIDITY: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_CONST_INLINE: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TOP_LOAD_CONST_INLINE: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_CONST_INLINE_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[0] = value;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_CALL: {
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_CALL_ONE: {
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_CALL_TWO: {
            stack_pointer += -4;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TOP_LOAD_CONST_INLINE_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_TWO_LOAD_CONST_INLINE_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-2] = value;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_CALL_LOAD_CONST_INLINE_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-2] = value;
            stack_pointer += -1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_CALL_ONE_LOAD_CONST_INLINE_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-3] = value;
            stack_pointer += -2;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _POP_CALL_TWO_LOAD_CONST_INLINE_BORROW: {
            JitOptPESymbol *value;
            value = sym_new_not_null(ctx);
            stack_pointer[-4] = value;
            stack_pointer += -3;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_CONST_UNDER_INLINE: {
            JitOptPESymbol *value;
            JitOptPESymbol *new;
            value = sym_new_not_null(ctx);
            new = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            stack_pointer[0] = new;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _LOAD_CONST_UNDER_INLINE_BORROW: {
            JitOptPESymbol *value;
            JitOptPESymbol *new;
            value = sym_new_not_null(ctx);
            new = sym_new_not_null(ctx);
            stack_pointer[-1] = value;
            stack_pointer[0] = new;
            stack_pointer += 1;
            assert(WITHIN_STACK_BOUNDS());
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _CHECK_FUNCTION: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _START_EXECUTOR: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _MAKE_WARM: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _FATAL_ERROR: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _DEOPT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _HANDLE_PENDING_AND_DEOPT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _ERROR_POP_N: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _TIER2_RESUME_CHECK: {
            COPY_TO_TRACE(this_instr);
            break;
        }

        case _COLD_EXIT: {
            COPY_TO_TRACE(this_instr);
            break;
        }

